services:
  pgdb:
    image: postgres:17.5-alpine
    container_name: pgdb
    environment:
      POSTGRES_DB: surfer_db
      POSTGRES_USER: surfer
      POSTGRES_PASSWORD: surfer
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U surfer -d surfer_db"]
      interval: 5s
      timeout: 10s
      retries: 5
